apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-svc-db
  namespace: test
spec:
  hosts:
  - database.domainname
  exportTo:
  - "."
  ports:
  - number: 1521
    name: tcp
    protocol: TCP
  location: MESH_EXTERNAL  
  resolution: STATIC
  endpoints:
  - address: 2.2.2.2
