apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: gateway-routing
spec:
  hosts:
  - database.domainname
  gateways:
  - mesh
  - istio-egressgateway
  http:
  - match:
    - port: 80
      gateways:
      - mesh
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: external-svc-db
        port:
          number: 80
      weight: 100
  - match:
    - port: 80
      gateways:
      - istio-egressgateway
    route:
    - destination:
        host: database.domainname
        port:
          number: 5432
      weight: 100